import "@radix-ui/themes/styles.css"
import "../styles/globals.css"
import { Theme } from "@radix-ui/themes"
import type { Metadata } from "next"
import dynamic from "next/dynamic"

// import MainNavbar from "../components/main-nav"
// import SideNavLeft from "../components/side-nav-left"
// import SideNavRight from "../components/side-nav-right"
import { ReactQueryProvider } from "./ReactQueryProvider"
const MainNavbar = dynamic(() => import("../components/main-nav"))
const SideNavLeft = dynamic(() => import("../components/side-nav-left"))
const SideNavRight = dynamic(() => import("../components/side-nav-right"))

export const metadata: Metadata = {
  title: "Worthy Store",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className="bg-neutral-900">
          <Theme>
            <MainNavbar />
            <div className="flex pt-24 absolute">
              <SideNavLeft />
              <div className={`w-[68vw] mx-10 mt-1 mb-20`}>{children}</div>
              <SideNavRight />
            </div>
          </Theme>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
